// eslint-disable-next-line import/no-anonymous-default-export
export default {
  GET_POST_DETAIL: "GET_POST_DETAIL",
  GET_POST_ALL: "GET_POST_ALL",
  GET_COMMENT_DETAIL: "GET_COMMENT_DETAIL",
  GET_PHOTO_DETAIL: "GET_PHOTO_DETAIL",
  TOGGLE_SIDE_DRAWER_SUCCESS: "TOGGLE_SIDE_DRAWER_SUCCESS",
  OPEN_SNACKBAR: "OPEN_SNACKBAR",
};
